# Generated by Django 5.2.5 on 2026-01-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory_newspost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='news.newscategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
