# Generated by Django 5.2.5 on 2026-01-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newspost_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['category', 'status', '-published_at'], name='news_newspo_categor_a5d2e0_idx'),
        ),
    ]
