# Generated by Django 5.2.5 on 2026-01-17 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspost_news_newspo_categor_a5d2e0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('fire', '🔥'), ('wow', '😮')], max_length=16, verbose_name='Реакция')),
                ('session_key', models.CharField(blank=True, default='', max_length=40, verbose_name='Session key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.newspost', verbose_name='Новость')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'indexes': [models.Index(fields=['post', 'reaction'], name='news_newsre_post_id_8f8d80_idx'), models.Index(fields=['post', 'user'], name='news_newsre_post_id_00df8a_idx'), models.Index(fields=['post', 'session_key'], name='news_newsre_post_id_8cd525_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'reaction', 'user'), name='uniq_post_reaction_user'), models.UniqueConstraint(condition=models.Q(('session_key__gt', '')), fields=('post', 'reaction', 'session_key'), name='uniq_post_reaction_session')],
            },
        ),
    ]
