# Generated by Django 5.2.5 on 2026-01-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Автор (текст)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор (пользователь)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Источник (название)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Источник (ссылка)'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['author_user'], name='news_newspo_author__ddee6c_idx'),
        ),
    ]
