# Generated by Django 5.2.5 on 2026-01-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspost_author_name_newspost_author_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение')], max_length=10, verbose_name='Тип блока')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='Подпись (необязательно)')),
                ('alt', models.CharField(blank=True, max_length=140, verbose_name='ALT (для SEO)')),
            ],
            options={
                'verbose_name': 'Блок новости',
                'verbose_name_plural': 'Блоки новости',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Источник (коротко)')),
                ('url', models.URLField(help_text='Полная ссылка с https://', verbose_name='Ссылка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='newspost',
            name='news_newspo_author__ddee6c_idx',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='source_url',
        ),
        migrations.AddField(
            model_name='newsblock',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='news.newspost', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.newspost', verbose_name='Новость'),
        ),
        migrations.AddIndex(
            model_name='newsblock',
            index=models.Index(fields=['post', 'sort_order'], name='news_newsbl_post_id_7f85c3_idx'),
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['post', 'sort_order'], name='news_newsso_post_id_07e0dc_idx'),
        ),
    ]
