# Generated by Django 5.2.5 on 2026-01-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsblock_newssource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Какой плейсхолдер заменяет: {{img:1}} соответствует номеру 1', verbose_name='Номер (1-5)')),
                ('image', models.ImageField(upload_to='news/body/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Изображение в тексте',
                'verbose_name_plural': 'Изображения в тексте',
                'ordering': ['position', 'sort_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='newsblock',
            name='post',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='name',
        ),
        migrations.AddField(
            model_name='newspost',
            name='content',
            field=models.TextField(blank=True, help_text='Можно вставлять картинки плейсхолдерами: {{img:1}} ... {{img:5}}', verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='title',
            field=models.CharField(default=1, max_length=160, verbose_name='Название источника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='news/cover/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(help_text='Полная ссылка, обязательно с https://', verbose_name='Ссылка'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['author_user'], name='news_newspo_author__ddee6c_idx'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newspost', verbose_name='Новость'),
        ),
        migrations.DeleteModel(
            name='NewsBlock',
        ),
        migrations.AddIndex(
            model_name='newsimage',
            index=models.Index(fields=['post', 'position'], name='news_newsim_post_id_f48b2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsimage',
            constraint=models.UniqueConstraint(fields=('post', 'position'), name='uniq_post_image_position'),
        ),
    ]
