# Generated by Django 5.2.5 on 2026-09-19 19:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('default_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент по умолчанию')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Владелец')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'verbose_name_plural': 'Категории расходов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Финансовый dashboard',
                'verbose_name_plural': 'Финансовый dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.employee',),
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.CharField(max_length=255, verbose_name='Категория / описание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Дополнительный доход',
                'verbose_name_plural': 'Дополнительные доходы',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='finance_oth_date_88ac78_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='finance_exp_date_677539_idx'), models.Index(fields=['category', 'date'], name='finance_exp_categor_d79319_idx')],
            },
        ),
        migrations.CreateModel(
            name='RepairFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(max_length=255, verbose_name='Описание ремонта')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Получено от клиента')),
                ('part_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость запчасти')),
                ('master_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сохраняется в ремонте и не меняется при изменении профиля исполнителя.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент исполнителя')),
                ('repair_margin', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Маржа до зарплаты')),
                ('master_salary', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Зарплата мастера')),
                ('workshop_profit', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Прибыль мастерской')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repairs', to='finance.employee', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Ремонт (финансы)',
                'verbose_name_plural': 'Ремонты (финансы)',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='finance_rep_date_dec3f4_idx'), models.Index(fields=['employee', 'date'], name='finance_rep_employe_680376_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('employee', models.ForeignKey(limit_choices_to={'is_owner': False}, on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='finance.employee', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплаты',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='finance_sal_employe_99c02d_idx')],
            },
        ),
    ]
