# Generated by Django 5.2.5 on 2026-09-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_partitem_supplier_repairfinance_manual_part_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcatalog',
            name='brand',
            field=models.CharField(blank=True, max_length=80, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='partcatalog',
            name='device_model',
            field=models.CharField(blank=True, max_length=120, verbose_name='Модель устройства'),
        ),
    ]
