# Generated by Django 5.2.5 on 2026-09-20 19:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_partcatalog_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала распределения')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Общая стоимость')),
                ('periods_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество расчётных периодов')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributed_expenses', to='finance.expensecategory', verbose_name='Категория')),
                ('employees', models.ManyToManyField(blank=True, limit_choices_to={'is_owner': False}, related_name='distributed_expenses', to='finance.employee', verbose_name='Мастера')),
                ('source_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution', to='finance.expense', verbose_name='Связанный реальный расход')),
            ],
            options={
                'verbose_name': 'Распределяемый расход',
                'verbose_name_plural': 'Распределяемые расходы',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Окончание периода')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=12, verbose_name='Статус')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата расчёта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Расчётный период',
                'verbose_name_plural': 'Расчётные периоды',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('start_date', 'end_date'), name='uniq_payroll_period_dates')],
            },
        ),
        migrations.CreateModel(
            name='PayrollCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairs_count', models.PositiveIntegerField(verbose_name='Ремонтов')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Выручка')),
                ('direct_costs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Прямые затраты')),
                ('repair_margin', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Маржа')),
                ('distributed_costs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Распределяемые расходы')),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='База зарплаты')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='К выплате')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Рассчитан')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_calculations', to='finance.employee', verbose_name='Мастер')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='finance.payrollperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Расчёт зарплаты',
                'verbose_name_plural': 'Расчёты зарплаты',
            },
        ),
        migrations.CreateModel(
            name='DistributedExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('distributed_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.distributedexpense', verbose_name='Распределяемый расход')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.payrollcalculation', verbose_name='Расчёт')),
            ],
            options={
                'verbose_name': 'Списание распределяемого расхода',
                'verbose_name_plural': 'Списания распределяемых расходов',
                'constraints': [models.UniqueConstraint(fields=('calculation', 'distributed_expense'), name='uniq_payroll_distribution')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollcalculation',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='uniq_period_employee_payroll'),
        ),
    ]
