# Generated by Django 5.2.5 on 2026-09-20 19:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_distributedexpense_payrollperiod_payrollcalculation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRepairSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField(verbose_name='Дата ремонта')),
                ('description', models.CharField(max_length=255, verbose_name='Описание ремонта')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма ремонта')),
                ('parts_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Запчасти')),
                ('other_direct_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Другие прямые затраты')),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='База')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент мастера')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Начислено')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_snapshots', to='finance.payrollcalculation', verbose_name='Расчёт')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_snapshots', to='finance.repairfinance', verbose_name='Исходный ремонт')),
            ],
            options={
                'verbose_name': 'Ремонт в закрытом расчёте зарплаты',
                'verbose_name_plural': 'Ремонты в закрытых расчётах зарплаты',
                'ordering': ['repair_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('calculation', 'repair'), name='uniq_payroll_repair_snapshot')],
            },
        ),
    ]
