# Generated by Django 5.2.5 on 2026-09-20 20:07

from decimal import Decimal
from django.db import migrations, models


def backfill_allocation_snapshots(apps, schema_editor):
    DistributedExpense = apps.get_model('finance', 'DistributedExpense')
    Allocation = apps.get_model('finance', 'DistributedExpenseAllocation')
    for expense in DistributedExpense.objects.all():
        allocations = list(
            Allocation.objects.filter(distributed_expense=expense)
            .select_related('calculation__period')
            .order_by('calculation__period__end_date', 'calculation__period_id', 'id')
        )
        cumulative = Decimal('0.00')
        period_number = 0
        current_period_id = None
        period_rows = []
        for allocation in allocations + [None]:
            period_id = allocation.calculation.period_id if allocation else None
            if period_rows and period_id != current_period_id:
                period_number += 1
                cumulative += sum((row.amount for row in period_rows), Decimal('0.00'))
                remaining = max(expense.total_cost - cumulative, Decimal('0.00'))
                Allocation.objects.filter(pk__in=[row.pk for row in period_rows]).update(
                    name_snapshot=expense.name,
                    total_cost_snapshot=expense.total_cost,
                    part_number=period_number,
                    parts_count=expense.periods_count,
                    accounted_after=cumulative,
                    remaining_after=remaining,
                )
                period_rows = []
            if allocation:
                current_period_id = period_id
                period_rows.append(allocation)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payrollrepairsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedexpenseallocation',
            name='accounted_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Учтено после расчёта'),
        ),
        migrations.AddField(
            model_name='distributedexpenseallocation',
            name='name_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название на момент расчёта'),
        ),
        migrations.AddField(
            model_name='distributedexpenseallocation',
            name='part_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер части'),
        ),
        migrations.AddField(
            model_name='distributedexpenseallocation',
            name='parts_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Всего частей'),
        ),
        migrations.AddField(
            model_name='distributedexpenseallocation',
            name='remaining_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Остаток после расчёта'),
        ),
        migrations.AddField(
            model_name='distributedexpenseallocation',
            name='total_cost_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Полная стоимость на момент расчёта'),
        ),
        migrations.RunPython(backfill_allocation_snapshots, migrations.RunPython.noop),
    ]
