# Generated by Django 5.2.5 on 2026-09-22 20:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='document_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Номер документа / транзакции'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('bank', 'Расчётный счёт'), ('other', 'Другое')], default='transfer', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='financial_resolution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма возврата / зачёта'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='financial_resolution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата финансовой корректировки'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='replacement_part_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_for_claims', to='finance.partitem', verbose_name='Деталь на замену'),
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата возврата')),
                ('reason', models.CharField(max_length=200, verbose_name='Причина')),
                ('status', models.CharField(choices=[('sent', 'Отправлено поставщику'), ('received', 'Поставщик получил'), ('review', 'Рассматривается'), ('replaced', 'Заменено'), ('refunded', 'Возврат денег'), ('credited', 'Зачтено'), ('rejected', 'Отказано')], default='sent', max_length=20, verbose_name='Статус')),
                ('financial_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата денег / зачёта')),
                ('financial_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма возврата / зачёта')),
                ('document_number', models.CharField(blank=True, max_length=120, verbose_name='Документ')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('part_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='finance.partitem', verbose_name='Деталь')),
                ('replacement_part_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_for_returns', to='finance.partitem', verbose_name='Деталь на замену')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='finance.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Возврат поставщику',
                'verbose_name_plural': 'Возвраты поставщикам',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['supplier', 'date'], name='finance_sup_supplie_5ebadb_idx')],
            },
        ),
    ]
