# Generated by Django 5.2.5 on 2026-09-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_supplierpayment_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время оплаты'),
        ),
    ]
