# Generated by Django 5.2.5 on 2026-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_supplierpayment_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Гарантия поставщика, дней'),
        ),
    ]
