# Generated by Django 5.2.5 on 2026-10-03 16:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_stockreceipt_warranty_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrepairsnapshot',
            name='distributed_cost_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Доля распределяемых расходов'),
        ),
        migrations.AddField(
            model_name='payrollrepairsnapshot',
            name='final_salary_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итоговое начисление'),
        ),
    ]
