# Generated by Django 5.2.5 on 2026-10-05 10:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_backfill_payroll_snapshot_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('part_name_snapshot', models.CharField(max_length=255, verbose_name='Материал на момент выдачи')),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=160, verbose_name='Поставщик на момент выдачи')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость единицы на момент выдачи')),
                ('total_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Общая стоимость на момент выдачи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_issues_created', to=settings.AUTH_USER_MODEL, verbose_name='Оформил')),
                ('distributed_expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_issue', to='finance.distributedexpense', verbose_name='Распределяемый расход')),
                ('employee', models.ForeignKey(limit_choices_to={'is_owner': False}, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_issues', to='finance.employee', verbose_name='Мастер')),
                ('source_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_issues', to='finance.stockreceipt', verbose_name='Поступление')),
            ],
            options={
                'verbose_name': 'Выдача со склада мастеру',
                'verbose_name_plural': 'Выдачи со склада мастерам',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='partitem',
            name='warehouse_issue',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.warehouseissue', verbose_name='Выдача мастеру'),
        ),
        migrations.AddIndex(
            model_name='warehouseissue',
            index=models.Index(fields=['employee', 'issue_date'], name='finance_war_employe_48b20e_idx'),
        ),
    ]
