# Generated by Django 5.2.5 on 2026-10-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountprofile_phone_verified_at_phoneverification'),
        ('repairs', '0013_alter_referralredemption_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='referral_partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_profile', to='repairs.referralpartner', verbose_name='Участник реферальной программы'),
        ),
    ]
