from django.urls import path

from . import views

app_name = "finance"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("repairs/", views.repair_list, name="repair_list"),
    path("repairs/add/", views.repair_create, name="repair_create"),
    path("repairs/<int:pk>/edit/", views.repair_edit, name="repair_edit"),
    path("repairs/<int:pk>/delete/", views.repair_delete, name="repair_delete"),
    path("expenses/", views.expense_list, name="expense_list"),
    path("expenses/add/", views.expense_create, name="expense_create"),
    path("expenses/<int:pk>/edit/", views.expense_edit, name="expense_edit"),
    path("expenses/<int:pk>/delete/", views.expense_delete, name="expense_delete"),
    path("expense-categories/", views.category_list, name="category_list"),
    path("expense-categories/add/", views.category_create, name="category_create"),
    path("expense-categories/<int:pk>/edit/", views.category_edit, name="category_edit"),
    path("expense-categories/<int:pk>/delete/", views.category_delete, name="category_delete"),
    path("income/", views.income_list, name="income_list"),
    path("income/add/", views.income_create, name="income_create"),
    path("income/<int:pk>/edit/", views.income_edit, name="income_edit"),
    path("income/<int:pk>/delete/", views.income_delete, name="income_delete"),
    path("masters/", views.master_list, name="master_list"),
    path("masters/add/", views.master_create, name="master_create"),
    path("masters/<int:pk>/edit/", views.master_edit, name="master_edit"),
    path("masters/<int:pk>/delete/", views.master_delete, name="master_delete"),
    path("masters/<int:pk>/access/create/", views.master_access_create, name="master_access_create"),
    path("masters/<int:pk>/access/password/", views.master_access_password, name="master_access_password"),
    path("masters/<int:pk>/access/toggle/", views.master_access_toggle, name="master_access_toggle"),
    path("masters/<int:pk>/percent/", views.employee_percent, name="employee_percent"),
    path("salaries/", views.salary_list, name="salary_list"),
    path("salaries/add/", views.salary_payment_create, name="salary_payment_create"),
    path("salaries/<int:pk>/edit/", views.salary_payment_edit, name="salary_payment_edit"),
    path("salaries/<int:pk>/delete/", views.salary_payment_delete, name="salary_payment_delete"),
    path("parts/", views.stock_list, name="stock_list"),
    path("parts/items/<int:pk>/", views.part_item_detail, name="part_item_detail"),
    path("parts/receipts/", views.receipt_list, name="receipt_list"),
    path("parts/receipts/add/", views.receipt_create, name="receipt_create"),
    path("parts/receipts/<int:pk>/edit/", views.receipt_edit, name="receipt_edit"),
    path("parts/catalog/", views.catalog_list, name="catalog_list"),
    path("parts/catalog/add/", views.catalog_create, name="catalog_create"),
    path("parts/catalog/<int:pk>/edit/", views.catalog_edit, name="catalog_edit"),
    path("parts/suppliers/", views.supplier_list, name="supplier_list"),
    path("parts/suppliers/add/", views.supplier_create, name="supplier_create"),
    path("parts/suppliers/<int:pk>/", views.supplier_detail, name="supplier_detail"),
    path("parts/suppliers/<int:pk>/edit/", views.supplier_edit, name="supplier_edit"),
    path("parts/suppliers/<int:pk>/delete/", views.supplier_delete, name="supplier_delete"),
    path("parts/supplier-payments/", views.supplier_payment_list, name="supplier_payment_list"),
    path("parts/supplier-payments/add/", views.supplier_payment_create, name="supplier_payment_create"),
    path("parts/supplier-payments/<int:pk>/edit/", views.supplier_payment_edit, name="supplier_payment_edit"),
    path("parts/supplier-payments/<int:pk>/delete/", views.supplier_payment_delete, name="supplier_payment_delete"),
    path("parts/warranty/", views.warranty_list, name="warranty_list"),
    path("parts/warranty/add/", views.warranty_create, name="warranty_create"),
    path("parts/warranty/<int:pk>/", views.warranty_detail, name="warranty_detail"),
    path("parts/warranty/<int:pk>/edit/", views.warranty_edit, name="warranty_edit"),
    path("expenses/distributed/", views.distributed_expense_list, name="distributed_expense_list"),
    path("expenses/distributed/add/", views.distributed_expense_create, name="distributed_expense_create"),
    path("expenses/distributed/<int:pk>/", views.distributed_expense_detail, name="distributed_expense_detail"),
    path("expenses/distributed/<int:pk>/edit/", views.distributed_expense_edit, name="distributed_expense_edit"),
    path("expenses/distributed/<int:pk>/finish/", views.distributed_expense_finish, name="distributed_expense_finish"),
    path("salaries/periods/", views.payroll_period_list, name="payroll_period_list"),
    path("salaries/periods/add/", views.payroll_period_create, name="payroll_period_create"),
    path("salaries/periods/<int:pk>/", views.payroll_period_detail, name="payroll_period_detail"),
    path("salaries/periods/<int:pk>/close/", views.payroll_period_close, name="payroll_period_close"),
]
