# Generated by Django 5.2.5 on 2026-09-23 21:18

import crm.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0010_supplierpayment_paid_at'),
        ('repairs', '0010_appointment_combo_discount_amount_appointmentitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMDocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(default='Техсфера', max_length=160, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('receipt_terms', models.TextField(blank=True, verbose_name='Условия приёма')),
                ('act_terms', models.TextField(blank=True, verbose_name='Текст акта')),
                ('warranty_terms', models.TextField(blank=True, verbose_name='Условия гарантии')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки документов CRM',
                'verbose_name_plural': 'Настройки документов CRM',
            },
        ),
        migrations.CreateModel(
            name='CRMIssueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CRMWorkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='Название')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена по умолчанию')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CRMClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('normalized_phone', models.CharField(db_index=True, max_length=20, verbose_name='Нормализованный телефон')),
                ('additional_phone', models.CharField(blank=True, max_length=40, verbose_name='Дополнительный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='Источник')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Клиент CRM',
                'verbose_name_plural': 'Клиенты CRM',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['name'], name='crm_crmclie_name_2a50f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CRMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=80, verbose_name='Тип устройства')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(blank=True, max_length=140, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='IMEI / SN')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='Цвет')),
                ('condition', models.TextField(blank=True, verbose_name='Состояние')),
                ('included_items', models.TextField(blank=True, verbose_name='Комплектность')),
                ('unlock_code', models.CharField(blank=True, max_length=255, verbose_name='Код устройства')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='crm.crmclient', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Устройство клиента',
                'verbose_name_plural': 'Устройства клиентов',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=9, unique=True, verbose_name='Номер заказа')),
                ('order_type', models.CharField(choices=[('paid', 'Платный'), ('warranty', 'Гарантийный')], default='paid', max_length=20, verbose_name='Тип заказа')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('diagnostic', 'Диагностика'), ('approval', 'Ожидает согласования'), ('waiting_part', 'Ожидает деталь'), ('repair', 'В ремонте'), ('ready', 'Готово к выдаче'), ('issued', 'Выдано'), ('canceled', 'Отказ / отмена')], db_index=True, default='accepted', max_length=20, verbose_name='Статус')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Принят')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Готов')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдан')),
                ('issue_description', models.TextField(verbose_name='Причина обращения')),
                ('diagnostic_result', models.TextField(blank=True, verbose_name='Результат диагностики')),
                ('internal_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('agreed_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Согласованная стоимость')),
                ('warranty_days', models.PositiveIntegerField(default=0, verbose_name='Гарантия, дней')),
                ('warranty_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало гарантии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.crmclient', verbose_name='Клиент')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.crmdevice', verbose_name='Устройство')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_orders', to='finance.employee', verbose_name='Мастер')),
                ('source_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_order', to='repairs.appointment', verbose_name='Онлайн-запись')),
                ('warranty_source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_orders', to='crm.crmorder', verbose_name='Исходный гарантийный ремонт')),
            ],
            options={
                'verbose_name': 'Заказ CRM',
                'verbose_name_plural': 'Заказы CRM',
                'ordering': ['-accepted_at', '-id'],
                'permissions': [('access_crm', 'Может входить в CRM'), ('view_all_orders', 'Может видеть все заказы CRM'), ('change_order_status', 'Может менять статусы CRM'), ('manage_documents', 'Может открывать документы CRM')],
            },
        ),
        migrations.CreateModel(
            name='CRMEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Заказ создан'), ('status', 'Статус изменён'), ('employee', 'Мастер изменён'), ('diagnostic', 'Диагностика изменена'), ('price', 'Цена изменена'), ('work', 'Работа изменена'), ('comment', 'Комментарий добавлен'), ('attachment', 'Файл добавлен'), ('warranty', 'Гарантия изменена'), ('document', 'Документ открыт')], max_length=24, verbose_name='Тип')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Было')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Стало')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.crmorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CRMComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_comments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.crmorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=crm.models.crm_attachment_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_attachments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.crmorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Работа')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='crm.crmorder', verbose_name='Заказ')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='crmdevice',
            index=models.Index(fields=['client', 'serial_number'], name='crm_crmdevi_client__a0a10a_idx'),
        ),
        migrations.AddIndex(
            model_name='crmorder',
            index=models.Index(fields=['status', 'accepted_at'], name='crm_crmorde_status_5c2acb_idx'),
        ),
        migrations.AddIndex(
            model_name='crmorder',
            index=models.Index(fields=['employee', 'status'], name='crm_crmorde_employe_7a2e27_idx'),
        ),
        migrations.AddIndex(
            model_name='crmorder',
            index=models.Index(fields=['order_type', 'accepted_at'], name='crm_crmorde_order_t_8e8a6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmorder',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_price__gte', 0)), name='crm_order_price_nonnegative'),
        ),
    ]
