# Generated by Django 5.2.5 on 2026-09-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Бренд CRM',
                'verbose_name_plural': 'Бренды CRM',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CRMDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип устройства CRM',
                'verbose_name_plural': 'Типы устройств CRM',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CRMWarrantyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(unique=True, verbose_name='Дней')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Срок гарантии CRM',
                'verbose_name_plural': 'Сроки гарантии CRM',
                'ordering': ['sort_order', 'days'],
            },
        ),
        migrations.AlterModelOptions(
            name='crmdocumentsettings',
            options={'permissions': [('manage_crm_settings', 'Может управлять настройками CRM')], 'verbose_name': 'Настройки документов CRM', 'verbose_name_plural': 'Настройки документов CRM'},
        ),
        migrations.AlterModelOptions(
            name='crmissuetemplate',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='crmworktemplate',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='crmissuetemplate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='crmworktemplate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='CRMDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='crm.crmbrand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель устройства CRM',
                'verbose_name_plural': 'Модели устройств CRM',
                'ordering': ['brand__sort_order', 'brand__name', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'name'), name='uniq_crm_brand_model')],
            },
        ),
    ]
