# Generated by Django 5.2.5 on 2026-09-27 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_seed_crm_settings'),
        ('finance', '0011_stockreceipt_warranty_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Заказ создан'), ('status', 'Статус изменён'), ('employee', 'Мастер изменён'), ('diagnostic', 'Диагностика изменена'), ('price', 'Цена изменена'), ('work', 'Работа изменена'), ('comment', 'Комментарий добавлен'), ('attachment', 'Файл добавлен'), ('warranty', 'Гарантия изменена'), ('document', 'Документ открыт'), ('part', 'Операция с деталью')], max_length=24, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='CRMOrderPartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная стоимость')),
                ('supplier_name_snapshot', models.CharField(max_length=160, verbose_name='Поставщик')),
                ('warranty_days_snapshot', models.PositiveIntegerField(default=0, verbose_name='Гарантия поставщика, дней')),
                ('status', models.CharField(choices=[('installed', 'Установлена'), ('removed', 'Возвращена на склад')], db_index=True, default='installed', max_length=16, verbose_name='Статус')),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='Установлена')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Возвращена')),
                ('finance_repair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_part_usages', to='finance.repairfinance', verbose_name='Финансовый ремонт')),
                ('installed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_crm_parts', to=settings.AUTH_USER_MODEL, verbose_name='Установил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_usages', to='crm.crmorder', verbose_name='Ремонт CRM')),
                ('part_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_usages', to='finance.partitem', verbose_name='Экземпляр детали')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_crm_parts', to=settings.AUTH_USER_MODEL, verbose_name='Вернул')),
            ],
            options={
                'verbose_name': 'Деталь в CRM-ремонте',
                'verbose_name_plural': 'Детали в CRM-ремонтах',
                'ordering': ['installed_at', 'id'],
                'indexes': [models.Index(fields=['order', 'status'], name='crm_crmorde_order_i_2b84f6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'installed')), fields=('part_item',), name='uniq_active_crm_part_usage'), models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0)), name='crm_part_usage_cost_nonnegative')],
            },
        ),
    ]
