# Generated by Django 5.2.5 on 2026-09-27 16:12

import core.storage
import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_crmevent_event_type_crmorderpartusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmattachment',
            name='file',
            field=models.FileField(storage=core.storage.PrivateMediaStorage(), upload_to=crm.models.crm_attachment_path, verbose_name='Файл'),
        ),
    ]
