# Generated by Django 5.2.5 on 2026-09-27 19:44

from django.db import migrations, models


def clear_completed_estimates(apps, schema_editor):
    CRMOrder = apps.get_model("crm", "CRMOrder")
    CRMOrder.objects.filter(status__in=["ready", "issued", "canceled"]).update(
        estimated_work_minutes_snapshot=None
    )


def restore_completed_estimates(apps, schema_editor):
    CRMOrder = apps.get_model("crm", "CRMOrder")
    CRMOrder.objects.filter(estimated_work_minutes_snapshot__isnull=True).update(
        estimated_work_minutes_snapshot=60
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_crmorder_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmorder',
            name='estimated_work_minutes_snapshot',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Внутренняя оценка трудоёмкости ремонта.', null=True, verbose_name='Плановое время работы, минут'),
        ),
        migrations.RunPython(clear_completed_estimates, restore_completed_estimates),
    ]
