# Generated by Django 5.2.5 on 2025-08-28 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0005_referralredemption_paid_at_referralredemption_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('link_code', models.CharField(blank=True, max_length=12, unique=True, verbose_name='Код привязки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='repairs.referralpartner', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Telegram партнёра',
                'verbose_name_plural': 'Telegram партнёров',
            },
        ),
    ]
