# Generated by Django 5.2.5 on 2025-08-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_tg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnertelegram',
            options={'ordering': ['-created_at'], 'verbose_name': 'TG-привязка партнёра', 'verbose_name_plural': 'TG-привязки партнёров'},
        ),
        migrations.RemoveField(
            model_name='partnertelegram',
            name='link_code',
        ),
        migrations.RemoveField(
            model_name='partnertelegram',
            name='username',
        ),
        migrations.AlterField(
            model_name='partnertelegram',
            name='chat_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Telegram chat_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnertelegram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
