# Generated by Django 5.2.5 on 2026-10-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_tg', '0002_alter_partnertelegram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertelegram',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Владение подтверждено'),
        ),
        migrations.AddField(
            model_name='partnertelegram',
            name='verified_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Подтверждённый телефон'),
        ),
    ]
