name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-to-vps
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            cd /home/deploy/apps/tehsfera

            # Если это «чистая» машина — клонируем.
            if [ ! -d .git ]; then
              git clone https://github.com/yur1on/price_calculator.git .
            fi

            # Обновляемся до свежего main
            git fetch --all --prune
            git reset --hard origin/main

            # Убедимся, что лежит .env.prod
            test -f .env.prod || { echo "ERROR: /home/deploy/apps/tehsfera/.env.prod не найден"; exit 1; }

            # Пересборка и запуск
            docker compose -f docker-compose.prod.yml up -d --build

            # Быстрый статус и немного диагностики
            docker compose -f docker-compose.prod.yml ps
            git rev-parse HEAD
