name: SSH Test

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: SSH ping
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            set -e
            echo "CONNECTED AS $(whoami) ON $(hostname)"
            ls -la /home/deploy/apps/tehsfera
